import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const glysa = localFont({
  src: "../assets/fonts/Glysa.otf",
  variable: "--font-glysa",
});

const lexend = localFont({
  src: "../assets/fonts/LexendDeca-VariableFont_wght.ttf",
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Contacts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${glysa.variable} ${lexend.variable} h-full antialiased`}
    >
      <body className="bg-main-100 text-white min-h-full min-w-94 flex flex-col">
        {children}
      </body>
    </html>
  );
}
